package vista;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import modelo.Peluche;
import modelo.Usuario;
import modelo.Tienda;
import javax.swing.JLabel;
import java.util.List;
import java.util.ArrayList;

import java.awt.Image;

import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author yepif
 */

public class FrmCatalogo extends javax.swing.JFrame {
    private Tienda tienda = new Tienda();
      private Usuario usuario;

    /**
     * Creates new form FrmCatalogo
     */
  public FrmCatalogo(Usuario usuario) {
    this.usuario = usuario;
    initComponents(); // primero los componentes gráficos

  panelCatalogo.setPreferredSize(new Dimension(1033, 3200));  // ← Aumenta este valor si no es suficiente
scrollCatalogo.setViewportView(panelCatalogo);


// Refresca los cambios en pantalla
panelCatalogo.revalidate();
panelCatalogo.repaint();

    // Cargar logo
    cargarImagen(jLabel57, "/Imagenes/Logo.png");

    // Cargar peluches desde archivo (si existen)
    try {
        tienda.cargarCatalogo();
    } catch (Exception ex) {
        ex.printStackTrace();
    }
cargarPeluches();

    JOptionPane.showMessageDialog(this, "Bienvenido, " + usuario.getNombres());

    // Crear panel visual para los peluches
    JPanel panelPeluches = new JPanel();
    panelPeluches.setLayout(new FlowLayout());
    panelPeluches.setBackground(Color.WHITE);


}

  


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        scrollCatalogo = new javax.swing.JScrollPane();
        panelCatalogo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        lblPerro = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lblGato = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lblFantasia = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lblOso = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        lvlCalificacion1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lvlNombre1 = new javax.swing.JLabel();
        lvlPrecio1 = new javax.swing.JLabel();
        lvlCategoria1 = new javax.swing.JLabel();
        lblcd1 = new javax.swing.JLabel();
        btnFavorito1 = new javax.swing.JButton();
        jLabel57 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        lvlCalificacion2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lvlNombre2 = new javax.swing.JLabel();
        lvlPrecio2 = new javax.swing.JLabel();
        lvlCategoria2 = new javax.swing.JLabel();
        lblcd2 = new javax.swing.JLabel();
        btnFavorito2 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jButton18 = new javax.swing.JButton();
        lvlCalificacion4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lvlNombre4 = new javax.swing.JLabel();
        lvlPrecio4 = new javax.swing.JLabel();
        lvlCategoria4 = new javax.swing.JLabel();
        lblcd4 = new javax.swing.JLabel();
        btnFavorito4 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jButton20 = new javax.swing.JButton();
        lvlCalificacion3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lvlNombre3 = new javax.swing.JLabel();
        lvlPrecio3 = new javax.swing.JLabel();
        lvlCategoria3 = new javax.swing.JLabel();
        lblcd3 = new javax.swing.JLabel();
        btnFavorito3 = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jButton22 = new javax.swing.JButton();
        lvlCalificacion5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lvlNombre5 = new javax.swing.JLabel();
        lvlPrecio5 = new javax.swing.JLabel();
        lvlCategoria5 = new javax.swing.JLabel();
        lblcd5 = new javax.swing.JLabel();
        btnFavorito5 = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jButton24 = new javax.swing.JButton();
        lvlCalificacion6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lvlNombre6 = new javax.swing.JLabel();
        lvlPrecio6 = new javax.swing.JLabel();
        lvlCategoria6 = new javax.swing.JLabel();
        lblcd6 = new javax.swing.JLabel();
        btnFavorito6 = new javax.swing.JButton();
        btnFavorito7 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scrollCatalogo.setPreferredSize(new java.awt.Dimension(1033, 1750));

        panelCatalogo.setPreferredSize(new java.awt.Dimension(1000, 1750));

        jLabel1.setText("FLUFFY CENTER");

        jLabel2.setBackground(new java.awt.Color(255, 0, 102));
        jLabel2.setText("🔎 ");

        jButton2.setText("👨");

        jButton3.setText("🛒");

        jButton4.setText("❌");

        jButton6.setText("CARRITO");

        jButton8.setText("DESEOS");

        jButton9.setText("PEDIDOS");

        jButton10.setText("INICIO");

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("LOS PELUCHES MAS BACANOS");

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("ENCUENTRA EL COMPAÑERO PERFECTO PARA CADA MOMENTO ESPECIAL");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("EXPLORAR COLECCION");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(417, 417, 417)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        lblPerro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PERRO.png"))); // NOI18N
        lblPerro.setText("jLabel5");

        jLabel10.setText("PERROS");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPerro, javax.swing.GroupLayout.PREFERRED_SIZE, 112, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblPerro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblGato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/GATO.png"))); // NOI18N
        lblGato.setText("jLabel5");

        jLabel11.setText("GATO");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGato, javax.swing.GroupLayout.PREFERRED_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(lblGato, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblFantasia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/UNICORNIO.png"))); // NOI18N
        lblFantasia.setText("jLabel5");

        jLabel12.setText("FANTASIA");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(18, 18, 18))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblOso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/OSO.png"))); // NOI18N
        lblOso.setText("jLabel5");

        jLabel13.setText("OSO");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOso, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(lblOso, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("AGREGAR AL CARRITO");

        lvlCalificacion1.setText("⭐⭐⭐⭐⭐");

        jLabel7.setBackground(new java.awt.Color(255, 0, 51));
        jLabel7.setForeground(new java.awt.Color(255, 0, 51));
        jLabel7.setText("OFERTA");

        lvlNombre1.setText("OSO TEDDY CLASICO");

        lvlPrecio1.setText("75000");

        lvlCategoria1.setText("Osos");

        lblcd1.setText("jLabel15");

        btnFavorito1.setBackground(new java.awt.Color(204, 204, 204));
        btnFavorito1.setText("❤");
        btnFavorito1.setBorder(null);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lvlNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lvlPrecio1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lvlCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lvlCalificacion1)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(262, 262, 262)
                                .addComponent(btnFavorito1)))
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblcd1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnFavorito1)
                        .addGap(0, 154, Short.MAX_VALUE))
                    .addComponent(lblcd1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(lvlNombre1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lvlCalificacion1)
                .addGap(2, 2, 2)
                .addComponent(lvlCategoria1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lvlPrecio1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel57.setText("jLabel57");

        jButton14.setText("BUSCAR");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jLabel5.setText("❤");

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setPreferredSize(new java.awt.Dimension(345, 339));

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("AGREGAR AL CARRITO");

        lvlCalificacion2.setText("⭐⭐⭐⭐⭐");

        jLabel8.setBackground(new java.awt.Color(255, 0, 51));
        jLabel8.setForeground(new java.awt.Color(255, 0, 51));
        jLabel8.setText("OFERTA");

        lvlNombre2.setText("OSO TEDDY CLASICO");

        lvlPrecio2.setText("75000");

        lvlCategoria2.setText("Osos");

        lblcd2.setText("jLabel15");

        btnFavorito2.setBackground(new java.awt.Color(204, 204, 204));
        btnFavorito2.setText("❤");
        btnFavorito2.setBorder(null);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lvlNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lvlPrecio2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lvlCategoria2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lvlCalificacion2)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(262, 262, 262)
                                .addComponent(btnFavorito2)))
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblcd2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnFavorito2)
                        .addGap(0, 154, Short.MAX_VALUE))
                    .addComponent(lblcd2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(lvlNombre2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lvlCalificacion2)
                .addGap(2, 2, 2)
                .addComponent(lvlCategoria2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lvlPrecio2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel12.setBackground(new java.awt.Color(204, 204, 204));
        jPanel12.setPreferredSize(new java.awt.Dimension(345, 339));

        jButton18.setBackground(new java.awt.Color(0, 0, 0));
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setText("AGREGAR AL CARRITO");

        lvlCalificacion4.setText("⭐⭐⭐⭐⭐");

        jLabel9.setBackground(new java.awt.Color(255, 0, 51));
        jLabel9.setForeground(new java.awt.Color(255, 0, 51));
        jLabel9.setText("OFERTA");

        lvlNombre4.setText("OSO TEDDY CLASICO");

        lvlPrecio4.setText("75000");

        lvlCategoria4.setText("Osos");

        lblcd4.setText("jLabel15");

        btnFavorito4.setBackground(new java.awt.Color(204, 204, 204));
        btnFavorito4.setText("❤");
        btnFavorito4.setBorder(null);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lvlNombre4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lvlPrecio4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lvlCategoria4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lvlCalificacion4)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(262, 262, 262)
                                .addComponent(btnFavorito4)))
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblcd4, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(btnFavorito4)
                        .addGap(0, 154, Short.MAX_VALUE))
                    .addComponent(lblcd4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(lvlNombre4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lvlCalificacion4)
                .addGap(2, 2, 2)
                .addComponent(lvlCategoria4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lvlPrecio4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel13.setBackground(new java.awt.Color(204, 204, 204));
        jPanel13.setPreferredSize(new java.awt.Dimension(345, 339));

        jButton20.setBackground(new java.awt.Color(0, 0, 0));
        jButton20.setForeground(new java.awt.Color(255, 255, 255));
        jButton20.setText("AGREGAR AL CARRITO");

        lvlCalificacion3.setText("⭐⭐⭐⭐⭐");

        jLabel14.setBackground(new java.awt.Color(255, 0, 51));
        jLabel14.setForeground(new java.awt.Color(255, 0, 51));
        jLabel14.setText("OFERTA");

        lvlNombre3.setText("OSO TEDDY CLASICO");

        lvlPrecio3.setText("75000");

        lvlCategoria3.setText("Osos");

        lblcd3.setText("jLabel15");

        btnFavorito3.setBackground(new java.awt.Color(204, 204, 204));
        btnFavorito3.setText("❤");
        btnFavorito3.setBorder(null);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lvlNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lvlPrecio3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lvlCategoria3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lvlCalificacion3)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(262, 262, 262)
                                .addComponent(btnFavorito3)))
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblcd3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(btnFavorito3)
                        .addGap(0, 154, Short.MAX_VALUE))
                    .addComponent(lblcd3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(lvlNombre3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lvlCalificacion3)
                .addGap(2, 2, 2)
                .addComponent(lvlCategoria3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lvlPrecio3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel16.setBackground(new java.awt.Color(204, 204, 204));
        jPanel16.setPreferredSize(new java.awt.Dimension(345, 339));

        jButton22.setBackground(new java.awt.Color(0, 0, 0));
        jButton22.setForeground(new java.awt.Color(255, 255, 255));
        jButton22.setText("AGREGAR AL CARRITO");

        lvlCalificacion5.setText("⭐⭐⭐⭐⭐");

        jLabel15.setBackground(new java.awt.Color(255, 0, 51));
        jLabel15.setForeground(new java.awt.Color(255, 0, 51));
        jLabel15.setText("OFERTA");

        lvlNombre5.setText("OSO TEDDY CLASICO");

        lvlPrecio5.setText("75000");

        lvlCategoria5.setText("Osos");

        lblcd5.setText("jLabel15");

        btnFavorito5.setBackground(new java.awt.Color(204, 204, 204));
        btnFavorito5.setText("❤");
        btnFavorito5.setBorder(null);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lvlNombre5, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lvlPrecio5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lvlCategoria5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lvlCalificacion5)
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(262, 262, 262)
                                .addComponent(btnFavorito5)))
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblcd5, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(btnFavorito5)
                        .addGap(0, 154, Short.MAX_VALUE))
                    .addComponent(lblcd5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(lvlNombre5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lvlCalificacion5)
                .addGap(2, 2, 2)
                .addComponent(lvlCategoria5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lvlPrecio5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel17.setBackground(new java.awt.Color(204, 204, 204));
        jPanel17.setPreferredSize(new java.awt.Dimension(345, 339));

        jButton24.setBackground(new java.awt.Color(0, 0, 0));
        jButton24.setForeground(new java.awt.Color(255, 255, 255));
        jButton24.setText("AGREGAR AL CARRITO");

        lvlCalificacion6.setText("⭐⭐⭐⭐⭐");

        jLabel16.setBackground(new java.awt.Color(255, 0, 51));
        jLabel16.setForeground(new java.awt.Color(255, 0, 51));
        jLabel16.setText("OFERTA");

        lvlNombre6.setText("OSO TEDDY CLASICO");

        lvlPrecio6.setText("75000");

        lvlCategoria6.setText("Osos");

        lblcd6.setText("jLabel15");

        btnFavorito6.setBackground(new java.awt.Color(204, 204, 204));
        btnFavorito6.setText("❤");
        btnFavorito6.setBorder(null);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lvlNombre6, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lvlPrecio6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lvlCategoria6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lvlCalificacion6)
                            .addGroup(jPanel17Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(262, 262, 262)
                                .addComponent(btnFavorito6)))
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblcd6, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addComponent(btnFavorito6)
                        .addGap(0, 154, Short.MAX_VALUE))
                    .addComponent(lblcd6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(lvlNombre6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lvlCalificacion6)
                .addGap(2, 2, 2)
                .addComponent(lvlCategoria6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lvlPrecio6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnFavorito7.setBackground(new java.awt.Color(204, 204, 204));
        btnFavorito7.setText("❤");
        btnFavorito7.setBorder(null);
        btnFavorito7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFavorito7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCatalogoLayout = new javax.swing.GroupLayout(panelCatalogo);
        panelCatalogo.setLayout(panelCatalogoLayout);
        panelCatalogoLayout.setHorizontalGroup(
            panelCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCatalogoLayout.createSequentialGroup()
                .addGap(342, 342, 342)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCatalogoLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(panelCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCatalogoLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(183, 183, 183)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFavorito7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCatalogoLayout.createSequentialGroup()
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 107, Short.MAX_VALUE))
                    .addGroup(panelCatalogoLayout.createSequentialGroup()
                        .addGroup(panelCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCatalogoLayout.createSequentialGroup()
                                .addGap(253, 253, 253)
                                .addComponent(jLabel5))
                            .addGroup(panelCatalogoLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(panelCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85))))
            .addGroup(panelCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCatalogoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panelCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelCatalogoLayout.createSequentialGroup()
                            .addGap(110, 110, 110)
                            .addComponent(jLabel1)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCatalogoLayout.createSequentialGroup()
                            .addGroup(panelCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelCatalogoLayout.createSequentialGroup()
                                    .addGap(89, 89, 89)
                                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelCatalogoLayout.createSequentialGroup()
                                    .addGap(79, 79, 79)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(311, 311, 311)))
                    .addContainerGap()))
        );
        panelCatalogoLayout.setVerticalGroup(
            panelCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCatalogoLayout.createSequentialGroup()
                .addGroup(panelCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCatalogoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCatalogoLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(panelCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton4)
                                .addComponent(jButton3)
                                .addComponent(jButton2)
                                .addComponent(jButton14)
                                .addComponent(btnFavorito7)))))
                .addGap(26, 26, 26)
                .addGroup(panelCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton8)
                    .addComponent(jButton6)
                    .addComponent(jButton10))
                .addGroup(panelCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCatalogoLayout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCatalogoLayout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCatalogoLayout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel5))
                    .addGroup(panelCatalogoLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(panelCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(panelCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(206, Short.MAX_VALUE))
            .addGroup(panelCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCatalogoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panelCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelCatalogoLayout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(116, 116, 116)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(188, 188, 188))
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(64, 64, 64)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(952, Short.MAX_VALUE)))
        );

        scrollCatalogo.setViewportView(panelCatalogo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollCatalogo, javax.swing.GroupLayout.DEFAULT_SIZE, 1021, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(scrollCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 1883, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
 String texto = txtBuscar.getText().trim().toLowerCase();

    // Oculta todos los labels por defecto
    lblcd1.setVisible(false);
    lblcd2.setVisible(false);
    lblcd3.setVisible(false);
    lblcd4.setVisible(false);
    lblcd5.setVisible(false);
    lblcd6.setVisible(false);

    // Opcional: Mostrar mensaje si está vacío
    if (texto.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingresa un nombre para buscar");
        return;
    }

    // Ahora mostramos solo el que coincide
    if ("teddy".contains(texto)) {
        lblcd1.setVisible(true);
    } else if ("gorila".contains(texto)) {
        lblcd2.setVisible(true);
    } else if ("siames".contains(texto)) {
        lblcd3.setVisible(true);
    } else if ("golden".contains(texto)) {
        lblcd4.setVisible(true);
    } else if ("stich".contains(texto)) {
        lblcd5.setVisible(true);
    } else if ("perronegro".contains(texto)) {
        lblcd6.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "No se encontró ningún peluche con ese nombre");
    }
        
    }//GEN-LAST:event_jButton14ActionPerformed

    private void btnFavorito7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFavorito7ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_btnFavorito7ActionPerformed

  private void cargarImagen(javax.swing.JLabel etiqueta, String ruta) {
    java.net.URL imgURL = getClass().getResource(ruta);
    if (imgURL == null) {
        System.err.println("No se encontró la imagen en: " + ruta);
        return;
    }
    
    ImageIcon icono = new ImageIcon(imgURL);
    Image imagen = icono.getImage().getScaledInstance(
        etiqueta.getWidth(), etiqueta.getHeight(), Image.SCALE_SMOOTH);
    etiqueta.setIcon(new ImageIcon(imagen));
}

 

public List<Peluche> buscarPeluches(String texto) {
    List<Peluche> resultado = new ArrayList<>();
    for (Peluche p : tienda.getCatalogo()) {
        if (p.getNombre().toLowerCase().contains(texto.toLowerCase())) {
            resultado.add(p);
        }
    }
    return resultado;
}

public void setTienda(Tienda tienda) {
    this.tienda = tienda;
}
ArrayList<Peluche> listaPeluches = new ArrayList<>();

// Este método se llama UNA VEZ (en el constructor)

 private void cargarPeluches() {
        ArrayList<Peluche> lista = tienda.getCatalogo();

        // Limitar a 6 peluches máximo para tus 6 paneles
        for (int i = 0; i < 6; i++) {
            if (i < lista.size()) {
                Peluche p = lista.get(i);
                switch(i) {
                    case 0: actualizarPanel(p, lblcd1, lvlNombre1, lvlPrecio1, lvlCategoria1, lvlCalificacion1); break;
                    case 1: actualizarPanel(p, lblcd2, lvlNombre2, lvlPrecio2, lvlCategoria2, lvlCalificacion2); break;
                    case 2: actualizarPanel(p, lblcd3, lvlNombre3, lvlPrecio3, lvlCategoria3, lvlCalificacion3); break;
                    case 3: actualizarPanel(p, lblcd4, lvlNombre4, lvlPrecio4, lvlCategoria4, lvlCalificacion4); break;
                    case 4: actualizarPanel(p, lblcd5, lvlNombre5, lvlPrecio5, lvlCategoria5, lvlCalificacion5); break;
                    case 5: actualizarPanel(p, lblcd6, lvlNombre6, lvlPrecio6, lvlCategoria6, lvlCalificacion6); break;
                }
            } else {
                // Limpiar panel si no hay peluche para ese índice
                switch(i) {
                    case 0: limpiarPanel(lblcd1, lvlNombre1, lvlPrecio1, lvlCategoria1, lvlCalificacion1); break;
                    case 1: limpiarPanel(lblcd2, lvlNombre2, lvlPrecio2, lvlCategoria2, lvlCalificacion2); break;
                    case 2: limpiarPanel(lblcd3, lvlNombre3, lvlPrecio3, lvlCategoria3, lvlCalificacion3); break;
                    case 3: limpiarPanel(lblcd4, lvlNombre4, lvlPrecio4, lvlCategoria4, lvlCalificacion4); break;
                    case 4: limpiarPanel(lblcd5, lvlNombre5, lvlPrecio5, lvlCategoria5, lvlCalificacion5); break;
                    case 5: limpiarPanel(lblcd6, lvlNombre6, lvlPrecio6, lvlCategoria6, lvlCalificacion6); break;
                }
            }
        }
    }

    private void actualizarPanel(Peluche p, JLabel lblImagen, JLabel lblNombre, JLabel lblPrecio, JLabel lblCategoria, JLabel lblCalificacion) {
        // Cargar imagen escalada
        ImageIcon icon = new ImageIcon(p.getImagenRuta());
        Image img = icon.getImage().getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), Image.SCALE_SMOOTH);
        lblImagen.setIcon(new ImageIcon(img));

        lblNombre.setText(p.getNombre());
        lblPrecio.setText(String.format("$ %.2f", p.getPrecio()));
        lblCategoria.setText(p.getCategoria());
        lblCalificacion.setText(String.format("⭐ %.1f", p.getCalificacion()));
    }

    private void limpiarPanel(JLabel lblImagen, JLabel lblNombre, JLabel lblPrecio, JLabel lblCategoria, JLabel lblCalificacion) {
        lblImagen.setIcon(null);
        lblNombre.setText("");
        lblPrecio.setText("");
        lblCategoria.setText("");
        lblCalificacion.setText("");
    }



public void mostrarPeluches() {
    ArrayList<Peluche> lista = tienda.getCatalogo();

    if (lista.size() >= 1) {
        Peluche p1 = lista.get(0);
        lvlNombre1.setText(p1.getNombre());
        lvlPrecio1.setText("$" + p1.getPrecio());
        lvlCategoria1.setText(p1.getCategoria());
        lvlCalificacion1.setText(p1.getCalificacion() + "★");
        btnFavorito1.addActionListener(e -> {
            usuario.agregarFavorito(p1);
            JOptionPane.showMessageDialog(this, p1.getNombre() + " fue añadido a tus favoritos.");
        });
    }

    if (lista.size() >= 2) {
        Peluche p2 = lista.get(1);
        lvlNombre2.setText(p2.getNombre());
        lvlPrecio2.setText("$" + p2.getPrecio());
        lvlCategoria2.setText(p2.getCategoria());
        lvlCalificacion2.setText(p2.getCalificacion() + "★");
        btnFavorito2.addActionListener(e -> {
            usuario.agregarFavorito(p2);
            JOptionPane.showMessageDialog(this, p2.getNombre() + " fue añadido a tus favoritos.");
        });
    }

    if (lista.size() >= 3) {
        Peluche p3 = lista.get(2);
        lvlNombre3.setText(p3.getNombre());
        lvlPrecio3.setText("$" + p3.getPrecio());
        lvlCategoria3.setText(p3.getCategoria());
        lvlCalificacion3.setText(p3.getCalificacion() + "★");
        btnFavorito3.addActionListener(e -> {
            usuario.agregarFavorito(p3);
            JOptionPane.showMessageDialog(this, p3.getNombre() + " fue añadido a tus favoritos.");
        });
    }

    if (lista.size() >= 4) {
        Peluche p4 = lista.get(3);
        lvlNombre4.setText(p4.getNombre());
        lvlPrecio4.setText("$" + p4.getPrecio());
        lvlCategoria4.setText(p4.getCategoria());
        lvlCalificacion4.setText(p4.getCalificacion() + "★");
        btnFavorito4.addActionListener(e -> {
            usuario.agregarFavorito(p4);
            JOptionPane.showMessageDialog(this, p4.getNombre() + " fue añadido a tus favoritos.");
        });
    }

    if (lista.size() >= 5) {
        Peluche p5 = lista.get(4);
        lvlNombre5.setText(p5.getNombre());
        lvlPrecio5.setText("$" + p5.getPrecio());
        lvlCategoria5.setText(p5.getCategoria());
        lvlCalificacion5.setText(p5.getCalificacion() + "★");
        btnFavorito5.addActionListener(e -> {
            usuario.agregarFavorito(p5);
            JOptionPane.showMessageDialog(this, p5.getNombre() + " fue añadido a tus favoritos.");
        });
    }

    if (lista.size() >= 6) {
        Peluche p6 = lista.get(5);
        lvlNombre6.setText(p6.getNombre());
        lvlPrecio6.setText("$" + p6.getPrecio());
        lvlCategoria6.setText(p6.getCategoria());
        lvlCalificacion6.setText(p6.getCalificacion() + "★");
        btnFavorito6.addActionListener(e -> {
            usuario.agregarFavorito(p6);
            JOptionPane.showMessageDialog(this, p6.getNombre() + " fue añadido a tus favoritos.");
        });
    }
}








    


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFavorito1;
    private javax.swing.JButton btnFavorito2;
    private javax.swing.JButton btnFavorito3;
    private javax.swing.JButton btnFavorito4;
    private javax.swing.JButton btnFavorito5;
    private javax.swing.JButton btnFavorito6;
    private javax.swing.JButton btnFavorito7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblFantasia;
    private javax.swing.JLabel lblGato;
    private javax.swing.JLabel lblOso;
    private javax.swing.JLabel lblPerro;
    private javax.swing.JLabel lblcd1;
    private javax.swing.JLabel lblcd2;
    private javax.swing.JLabel lblcd3;
    private javax.swing.JLabel lblcd4;
    private javax.swing.JLabel lblcd5;
    private javax.swing.JLabel lblcd6;
    private javax.swing.JLabel lvlCalificacion1;
    private javax.swing.JLabel lvlCalificacion2;
    private javax.swing.JLabel lvlCalificacion3;
    private javax.swing.JLabel lvlCalificacion4;
    private javax.swing.JLabel lvlCalificacion5;
    private javax.swing.JLabel lvlCalificacion6;
    private javax.swing.JLabel lvlCategoria1;
    private javax.swing.JLabel lvlCategoria2;
    private javax.swing.JLabel lvlCategoria3;
    private javax.swing.JLabel lvlCategoria4;
    private javax.swing.JLabel lvlCategoria5;
    private javax.swing.JLabel lvlCategoria6;
    private javax.swing.JLabel lvlNombre1;
    private javax.swing.JLabel lvlNombre2;
    private javax.swing.JLabel lvlNombre3;
    private javax.swing.JLabel lvlNombre4;
    private javax.swing.JLabel lvlNombre5;
    private javax.swing.JLabel lvlNombre6;
    private javax.swing.JLabel lvlPrecio1;
    private javax.swing.JLabel lvlPrecio2;
    private javax.swing.JLabel lvlPrecio3;
    private javax.swing.JLabel lvlPrecio4;
    private javax.swing.JLabel lvlPrecio5;
    private javax.swing.JLabel lvlPrecio6;
    private javax.swing.JPanel panelCatalogo;
    private javax.swing.JScrollPane scrollCatalogo;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
