
package vista;

import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;
import modelo.Peluche;
import modelo.Usuario;


public class FrmFavoritos extends javax.swing.JFrame {
 private Usuario usuario;
    /**
     * Creates new form FrmFavoritos
     */
    public FrmFavoritos(Usuario usuario1) {
      this.usuario = usuario;
        mostrarFavoritos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelFavoritos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelFavoritosLayout = new javax.swing.GroupLayout(panelFavoritos);
        panelFavoritos.setLayout(panelFavoritosLayout);
        panelFavoritosLayout.setHorizontalGroup(
            panelFavoritosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 967, Short.MAX_VALUE)
        );
        panelFavoritosLayout.setVerticalGroup(
            panelFavoritosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panelFavoritos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 957, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarFavoritos() {
        panelFavoritos.setLayout(new GridLayout(0, 1, 10, 10)); // Mostrar verticalmente

        for (Peluche p : usuario.getFavoritos()) {
            JPanel tarjeta = new JPanel();
            tarjeta.setLayout(new GridLayout(4, 1));
            tarjeta.setBorder(BorderFactory.createLineBorder(Color.GRAY));

            tarjeta.add(new JLabel("Nombre: " + p.getNombre()));
            tarjeta.add(new JLabel("Precio: $" + p.getPrecio()));
            tarjeta.add(new JLabel("Categoría: " + p.getCategoria()));
            tarjeta.add(new JLabel("Calificación: " + p.getCalificacion() + "★"));

            panelFavoritos.add(tarjeta);
        }

        panelFavoritos.revalidate();
        panelFavoritos.repaint();
    }

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelFavoritos;
    // End of variables declaration//GEN-END:variables
}
