/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.BorderLayout;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import modelo.Pedido;
import modelo.Tienda;

/**
 *
 * @author yepif
 */


public class FrmPedidos extends JFrame {

    private Tienda tienda;
    
    private DefaultTableModel modeloTabla;
    
    

    public FrmPedidos(Tienda tienda) {
    this.tienda = tienda;
    initComponents(); // NetBeans inicializa aquí tablaPedidos, botones, etc.

    // Ya puedes usar tablaPedidos
    modeloTabla = new DefaultTableModel(
        new Object[]{"ID", "Cliente", "Total", "Estado"}, 0
    );
    tablaPedidos.setModel(modeloTabla);

    cargarPedidos();

    // Asignar acciones
    btnEliminar.addActionListener(e -> eliminarPedido());
    btnMarcarEnviado.addActionListener(e -> marcarPedidoComoEnviado());

    setLocationRelativeTo(null); // Centrar ventana
    setTitle("Gestión de Pedidos");
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaPedidos = new javax.swing.JTable();
        btnEliminarPedido = new javax.swing.JButton();
        btnMarcarEnviado = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablaPedidos);

        btnEliminarPedido.setText("Eliminar pedido");
        btnEliminarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPedidoActionPerformed(evt);
            }
        });

        btnMarcarEnviado.setText("Marcar como Enviado");
        btnMarcarEnviado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcarEnviadoActionPerformed(evt);
            }
        });

        btnEliminar.setText("Cerrar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnMarcarEnviado)
                        .addGap(60, 60, 60)
                        .addComponent(btnEliminarPedido)
                        .addGap(402, 402, 402))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEliminar)
                        .addGap(203, 203, 203))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMarcarEnviado)
                    .addComponent(btnEliminarPedido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 701, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnMarcarEnviadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcarEnviadoActionPerformed
int fila = tablaPedidos.getSelectedRow();
if (fila >= 0) {
    int id = (int) tablaPedidos.getValueAt(fila, 0);
    Pedido pedido = tienda.buscarPedidoPorId(id);
    if (pedido != null) {
        pedido.setEstado("Enviado");
        tienda.guardarPedidos();
        cargarPedidos();
    }
} else {
    JOptionPane.showMessageDialog(this, "Selecciona un pedido primero.");
}

        // TODO add your handling code here:
    }//GEN-LAST:event_btnMarcarEnviadoActionPerformed

    private void btnEliminarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPedidoActionPerformed
                                             
    int fila = tablaPedidos.getSelectedRow();
    
    if (fila >= 0) {
        int confirmacion = JOptionPane.showConfirmDialog(this,
            "¿Estás seguro de que deseas eliminar este pedido?",
            "Confirmar eliminación",
            JOptionPane.YES_NO_OPTION);
        
        if (confirmacion == JOptionPane.YES_OPTION) {
            int id = (int) tablaPedidos.getValueAt(fila, 0);
            tienda.eliminarPedido(id);
            tienda.guardarPedidos();
            cargarPedidos();
            JOptionPane.showMessageDialog(this, "Pedido eliminado correctamente.");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Selecciona un pedido primero.");
    }



        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarPedido;
    private javax.swing.JButton btnMarcarEnviado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tablaPedidos;
    // End of variables declaration//GEN-END:variables
private void cargarPedidos() {
    modeloTabla.setRowCount(0); // Limpiar tabla
    List<Pedido> pedidos = tienda.getListaPedidos();

    System.out.println("Pedidos cargados: " + pedidos.size()); // ← TEMPORAL

    for (Pedido p : pedidos) {
        modeloTabla.addRow(new Object[]{
            p.getId(),
            p.getCliente().getUsername(),
            p.getTotal(),
            p.getEstado()
        });
    }
}



    private void marcarPedidoComoEnviado() {
        int fila = tablaPedidos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un pedido.");
            return;
        }

        int id = (int) modeloTabla.getValueAt(fila, 0);
        Pedido pedido = tienda.buscarPedidoPorId(id); // Método supuesto
        if (pedido != null) {
            pedido.setEstado("Enviado");
            cargarPedidos();
            JOptionPane.showMessageDialog(this, "Pedido marcado como enviado.");
        }
    }

    private void eliminarPedido() {
        int fila = tablaPedidos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un pedido.");
            return;
        }

        int id = (int) modeloTabla.getValueAt(fila, 0);
        int confirmar = JOptionPane.showConfirmDialog(this, "¿Eliminar el pedido?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (confirmar == JOptionPane.YES_OPTION) {
            tienda.eliminarPedido(id); // Método supuesto
            cargarPedidos();
            JOptionPane.showMessageDialog(this, "Pedido eliminado.");
        }
    }
   

}
