/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author yepif
 */


import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import modelo.Peluche;
import modelo.UsuarioDatos;
import modelo.TiendaDatos;
import modelo.VentaDatos;

public class FrmReportes extends JFrame {

    private JLabel lblTitulo, lblUsuarios, lblPeluches, lblVentas;
    private JButton btnCerrar;

    public FrmReportes() {
        setTitle("Reportes y Análisis");
        setSize(400, 300);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLayout(null);
        getContentPane().setBackground(new Color(240, 228, 255)); // Color lavanda claro

        // Título
        lblTitulo = new JLabel("Panel de Reportes", SwingConstants.CENTER);
        lblTitulo.setFont(new Font("Arial", Font.BOLD, 20));
        lblTitulo.setBounds(50, 20, 300, 30);
        add(lblTitulo);

        // Reportes
        lblUsuarios = new JLabel();
        lblUsuarios.setBounds(50, 70, 300, 25);
        lblUsuarios.setFont(new Font("Arial", Font.PLAIN, 16));
        add(lblUsuarios);

        lblPeluches = new JLabel();
        lblPeluches.setBounds(50, 110, 300, 25);
        lblPeluches.setFont(new Font("Arial", Font.PLAIN, 16));
        add(lblPeluches);

        lblVentas = new JLabel("Ventas totales: $727,828,727"); // Puedes reemplazar esto por lógica real
        lblVentas.setBounds(50, 150, 300, 25);
        lblVentas.setFont(new Font("Arial", Font.PLAIN, 16));
        add(lblVentas);

        // Botón cerrar
        btnCerrar = new JButton("Cerrar");
        btnCerrar.setBounds(150, 200, 100, 30);
        btnCerrar.addActionListener(e -> dispose());
        add(btnCerrar);

        // Cargar datos reales
        cargarDatos();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmReportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
private void cargarDatos() {
    int totalUsuarios = UsuarioDatos.cargarUsuarios().size();

    // Cargar peluches desde archivo y actualizar lista en memoria
    ArrayList<Peluche> peluches = TiendaDatos.cargarPeluches();
    int totalModelos = peluches.size();
    int totalStock = 0;

    for (Peluche p : peluches) {
        totalStock += p.getStock();
    }

    double totalVentas = VentaDatos.obtenerTotalVentas();

    lblUsuarios.setText("Usuarios registrados: " + totalUsuarios);
    lblPeluches.setText("Peluches en inventario: " + totalModelos + " modelos (" + totalStock + " unidades)");
    lblVentas.setText("Ventas totales: $" + String.format("%,.2f", totalVentas));
}




}

